#!/usr/bin/env bash
# Install cloudflared, create a named Cloudflare Tunnel, and enable systemd.
# Run ON Manus (Linux) as root: sudo bash deploy/cloudflared-manus.sh
#
# Manus blocks inbound 80/443 — this tunnel exposes Brain (localhost:8000) via Cloudflare.
# Prerequisites: conradstrong.com on Cloudflare; Brain healthy at http://127.0.0.1:8000/health
set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-conradstrong-brain}"
ORIGIN_URL="${ORIGIN_URL:-http://127.0.0.1:8000}"
PRIMARY_DOMAIN="${PRIMARY_DOMAIN:-conradstrong.com}"
WWW_DOMAIN="${WWW_DOMAIN:-www.conradstrong.com}"
CLOUDFLARED_USER="${CLOUDFLARED_USER:-cloudflared}"
CLOUDFLARED_GROUP="${CLOUDFLARED_GROUP:-cloudflared}"
CONFIG_DIR="/etc/cloudflared"
CONFIG_FILE="${CONFIG_DIR}/config.yml"
CRED_DIR="${CONFIG_DIR}"
SERVICE_FILE="/etc/systemd/system/cloudflared.service"

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

if [ "$(id -u)" -ne 0 ]; then
  die "Run as root: sudo bash $0"
fi

if ! curl -sf "${ORIGIN_URL}/health" >/dev/null 2>&1; then
  die "Brain not reachable at ${ORIGIN_URL}/health — start superman-brain first."
fi

install_cloudflared() {
  if command -v cloudflared >/dev/null 2>&1; then
    info "cloudflared already installed: $(cloudflared --version 2>&1 | head -1)"
    return
  fi

  info "Installing cloudflared…"
  if [ -f /etc/debian_version ]; then
    mkdir -p /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
      | gpg --dearmor -o /usr/share/keyrings/cloudflare-main.gpg
    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' \
      > /etc/apt/sources.list.d/cloudflared.list
    apt-get update -qq
    apt-get install -y cloudflared
  else
    ARCH="$(uname -m)"
    case "$ARCH" in
      x86_64)  CF_ARCH=amd64 ;;
      aarch64|arm64) CF_ARCH=arm64 ;;
      *) die "Unsupported arch: $ARCH" ;;
    esac
    TMP="$(mktemp)"
    curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${CF_ARCH}" -o "$TMP"
    install -m 0755 "$TMP" /usr/local/bin/cloudflared
    rm -f "$TMP"
  fi
  command -v cloudflared >/dev/null || die "cloudflared install failed"
}

authenticate() {
  if [ -f "${CRED_DIR}/cert.pem" ]; then
    info "Cloudflare account cert already present (${CRED_DIR}/cert.pem)"
    return
  fi
  info "Authenticate with Cloudflare (browser will open or URL printed)…"
  cloudflared tunnel login
  [ -f "${CRED_DIR}/cert.pem" ] || die "Login failed — cert.pem not found in ${CRED_DIR}"
}

ensure_tunnel() {
  if cloudflared tunnel list 2>/dev/null | awk '{print $1}' | grep -qx "$TUNNEL_NAME"; then
    info "Tunnel '${TUNNEL_NAME}' already exists"
  else
    info "Creating tunnel '${TUNNEL_NAME}'…"
    cloudflared tunnel create "$TUNNEL_NAME"
  fi

  TUNNEL_ID="$(cloudflared tunnel list | awk -v n="$TUNNEL_NAME" '$0 ~ n {print $1; exit}')"
  [ -n "$TUNNEL_ID" ] || die "Could not resolve tunnel ID for ${TUNNEL_NAME}"
  info "Tunnel ID: ${TUNNEL_ID}"

  CRED_JSON="${CRED_DIR}/${TUNNEL_ID}.json"
  if [ ! -f "$CRED_JSON" ]; then
    # cloudflared tunnel create writes credentials; locate if path differs
    FOUND="$(find "${CRED_DIR}" -maxdepth 1 -name '*.json' -newer "${CRED_DIR}/cert.pem" 2>/dev/null | head -1 || true)"
    [ -n "$FOUND" ] && CRED_JSON="$FOUND"
  fi
  [ -f "$CRED_JSON" ] || die "Tunnel credentials not found at ${CRED_DIR}/${TUNNEL_ID}.json"

  mkdir -p "$CONFIG_DIR"
  cat >"$CONFIG_FILE" <<EOF
# Generated by deploy/cloudflared-manus.sh — Conrad Brain on Manus
tunnel: ${TUNNEL_ID}
credentials-file: ${CRED_JSON}

ingress:
  - hostname: ${PRIMARY_DOMAIN}
    service: ${ORIGIN_URL}
  - hostname: ${WWW_DOMAIN}
    service: ${ORIGIN_URL}
  - service: http_status:404
EOF
  chmod 600 "$CONFIG_FILE"
  info "Wrote ${CONFIG_FILE}"
}

route_dns() {
  info "Routing DNS for ${PRIMARY_DOMAIN} and ${WWW_DOMAIN} (requires domain on Cloudflare account)…"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$PRIMARY_DOMAIN" || \
    echo "WARN: Could not auto-route ${PRIMARY_DOMAIN} — add CNAME in Cloudflare dashboard."
  cloudflared tunnel route dns "$TUNNEL_NAME" "$WWW_DOMAIN" || \
    echo "WARN: Could not auto-route ${WWW_DOMAIN} — add CNAME in Cloudflare dashboard."
}

install_systemd() {
  id "$CLOUDFLARED_USER" &>/dev/null || useradd --system --home "$CONFIG_DIR" --shell /usr/sbin/nologin "$CLOUDFLARED_USER"
  chown -R "${CLOUDFLARED_USER}:${CLOUDFLARED_GROUP}" "$CONFIG_DIR" 2>/dev/null || true
  chmod 600 "${CONFIG_DIR}"/*.json "${CONFIG_DIR}/cert.pem" 2>/dev/null || true

  cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=Cloudflare Tunnel (${TUNNEL_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
User=${CLOUDFLARED_USER}
Group=${CLOUDFLARED_GROUP}
ExecStart=$(command -v cloudflared) --config ${CONFIG_FILE} tunnel run
Restart=on-failure
RestartSec=5
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable cloudflared
  systemctl restart cloudflared
  sleep 2
  systemctl is-active --quiet cloudflared || {
    journalctl -u cloudflared -n 20 --no-pager
    die "cloudflared service failed to start"
  }
  info "cloudflared systemd service active"
}

main() {
  install_cloudflared
  authenticate
  ensure_tunnel
  route_dns
  install_systemd

  echo ""
  echo "OK — Cloudflare Tunnel '${TUNNEL_NAME}' → ${ORIGIN_URL}"
  echo "Next:"
  echo "  1. Cloudflare SSL/TLS → Full"
  echo "  2. Remove A record for @ → 102.210.17.121 if present"
  echo "  3. curl -sf https://${PRIMARY_DOMAIN}/health"
  echo ""
  echo "Logs: journalctl -u cloudflared -f"
}

main "$@"
